spring.application.name=Transport Reporting System


spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/transport_reporting_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:iradukunda}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${SERVER_PORT:8086}

# JWT Configuration
application.security.jwt.secret-key=${JWT_SECRET:NDk3NjQ5MmQ0YjYxNzQ2ODY1NzI2OTZlNjU1NDcyNjE2ZTNzNzA2ZjcyNzQ0MTcwNjk0YjY1Nzk=}
application.security.jwt.expiration=${JWT_EXPIRATION:86400000}
application.security.jwt.refresh-token.expiration=${JWT_REFRESH_EXPIRATION:604800000}

# Mail Configuration
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:inespatiente5@gmail.com}
spring.mail.password=${MAIL_PASSWORD:trco cniq zgbz cewt}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# 2FA Configuration
application.security.2fa.code-expiration=${TWO_FA_EXPIRATION:300000}
